version: '3.8'
services:
  nginx:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: nginx-server
    restart: always
    ports:
      - "4200:4200"
    volumes:
      - html:/usr/share/nginx/html/
volumes:
  html: {}
      